### ISSUE TITLE
Entwine doesn't appear to be happy with Xcode 11.2/Swift 5.1

### ISSUE THREAD

**Issue by heckj** [tcldr/Entwine#14]
I just updated Xcode to the 11.2 release, and while I suspect you already know, it seems there's some quirks that make Entwine a little less effective. Tests that passed previously are exploding now - I'm getting an `EXC_BAD_ACCESS` on TestablePublisherSubscription - I wasn't sure how to capture the information to best share, so I grabbed a screenshot Xcode dropping into the debugger. I'll poke a bit more, as maybe it's something stupid I've done - but I suspect it's in the queue'd side effects of Xcode 11.2 release

<img width="1405" alt="Screen Shot 2019-11-02 at 11 52 41 AM" src="https://user-images.githubusercontent.com/43388/68075631-8c5ee980-fd67-11e9-8fea-1caafde4582e.png">

**Comment by heckj** [comment]
(this is with the `master` branch on github.com/heckj/swiftui-notes - the one test where I'm using Entwine is blowing up - `EntwineTestExampleTests`)

**Comment by tcldr** [comment]
Hi @heckj!

Yes, this is a nasty one. It’s a swift PM bug (SR-11564). It must be affecting most projects which make use of SPM – but there’s a workaround.

More here:  https://bugs.swift.org/plugins/servlet/mobile#issue/SR-11564

I’ll leave this open until we get a fix from Apple so anyone else who might be troubleshooting this issue has a reference.

**Comment by tcldr** [comment]
Maybe helpful to say the workaround is to set ‘DEAD_CODE_STRIPPING = NO’ in your project build settings until we get a fix for SR-11564.

**Comment by heckj** [comment]
Thanks @tcldr - that definitely helped for the workaround! I appreciate the detail, since I'd seen some twitter conversations, but hadn't worked back to SR-11564

**Comment by tcldr** [comment]
This should now be resolved with Xcode 11.3; dead code stripping can be re-enabled!
