### ISSUE TITLE
TestablePublisher failed after receiving subscriptions . 

### ISSUE THREAD

**Issue by abdelmajidrajad** [tcldr/Entwine#15]
I tried to play with examples you cited in documentation and the testMap() example failed for me . 
the program stop here : 
 `func request(_ demand: Subscribers.Demand) {
        _ = queue?.requestDemand(demand)
 }`

I'm using xcode 11.2.1

**Comment by tcldr** [comment]
Maybe something to do with [SR-11564](https://bugs.swift.org/plugins/servlet/mobile#issue/SR-11564) and described in issue #14?

Try setting ‘DEAD_CODE_STRIPPING = NO’ in your project build settings and see if that resolves the issue.

**Comment by abdelmajidrajad** [comment]
Thanks. 
This resolve the issue .
