### ISSUE TITLE
`swift test` failing out of the box with the repo on Mojave

### ISSUE THREAD

**Issue by heckj** [tcldr/Entwine#3]
I cloned the repo and immediately tried:
- `swift build`
- `swift test`

it builds just fine, but on MacOS 10.14.5 (Mojave), the swift test fails, even with the correct swift being invoked:

`swift -v`:

```
Apple Swift version 5.1 (swiftlang-1100.0.43.3 clang-1100.0.26.3)
Target: x86_64-apple-darwin18.6.0
/Users/heckj/Applications/Xcode-beta.app/Contents/Developer/usr/bin/lldb "--repl=-enable-objc-interop -sdk /Users/heckj/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -color-diagnostics"
```

And the failure: `swift test`

```
2019-07-01 21:44:52.259 xctest[9733:44482] The bundle “EntwinePackageTests.xctest” couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle.
2019-07-01 21:44:52.259 xctest[9733:44482] (dlopen_preflight(/Users/heckj/src/Entwine/.build/x86_64-apple-macosx/debug/EntwinePackageTests.xctest/Contents/MacOS/EntwinePackageTests): Library not loaded: /System/Library/Frameworks/Combine.framework/Versions/A/Combine
  Referenced from: /Users/heckj/src/Entwine/.build/x86_64-apple-macosx/debug/EntwinePackageTests.xctest/Contents/MacOS/EntwinePackageTests
  Reason: image not found)
```

This may be something where swift test isn't respecting the platform constraint that you have defined in Package.swift (`.macOS(.v10_15)`), but I wasn't entire sure - so thought I'd mention it here.

**Comment by tcldr** [comment]
Hi there again – thanks for opening the issue!

Unfortunately it's not possible to test against macOS 10.14 as it won't find the Combine framework in the search path for the OS. It's not part of Swift, but rather a system framework.

If you want to run the tests on Mojave, your best bet is to open the package in Xcode 11 and run on an iOS simulator. (The iOS 13 SDK includes Combine.)
