### ISSUE TITLE
Could not find module 'Entwine' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator

### ISSUE THREAD

**Issue by koogawa** [tcldr/Entwine#32]
Xcode 12.5 running on Macbook Pro M1 (Big Sur)
Added Entwine v0.9.1 via Swift Package Manager

sample usage:

```
import Foundation
import Combine
import Entwine

final class Foo {
      ....
      ....
}
```

Error pops up when building (target device: iPhone 12 (14.5) simulator)

Tried:

- Clean build
- Restart XCode
- Adding `Any iOS Simulator SDK` with value `arm64` inside `Excluded Architecture`

**Comment by tcldr** [comment]
Hi @koogawa ,

Thanks for your bug report. Unfortunately I'm not able to reproduce your issue.

I've just tried:
  1. setting up a brand new project (Xcode 12.5)
  2. adding Entwine as a dependency
  3. creating a new class with the imports you mention above
  4. Set build target to iPhone 12
  5. Build on M1 Mac Mini running Big Sur (11.4)

I'm getting no build errors. Can you give me anything else to help me reproduce?

**Comment by koogawa** [comment]
Hi @tcldr ,

Thank you for your quick reply. Do you open Xcode using Rosetta?

![image](https://user-images.githubusercontent.com/893643/121080562-85873b00-c816-11eb-809a-963ed4958af0.png)

**Comment by tcldr** [comment]
I’d missed that you’re opening it under Rosetta.

Theoretically there shouldn’t be an issue running Entwine, or any other swift package, in this way.

However, I haven’t tried it myself.

Have you tried looking at this thread here:

https://forums.swift.org/t/xcode-12-2-spm-swift-nio-fails-to-build-for-apple-silicon-arm64/42197/24

**Comment by koogawa** [comment]
> https://forums.swift.org/t/xcode-12-2-spm-swift-nio-fails-to-build-for-apple-silicon-arm64/42197/24

I tried everything but it didn't work.

**Comment by koogawa** [comment]
I found similar issue https://github.com/ReactiveX/RxSwift/issues/2261

**Comment by tcldr** [comment]
Hi @koogawa ,

RxSwift seemed to resolve the issue by modifying their Xcode build settings. However, as Entwine is a Swift Package it doesn't have any build settings – or rather, the build settings are managed by the consuming Xcode project.

In any case, I tried to reproduce your issue with Xcode in Rosetta mode. But again, I couldn't reproduce.

What happens when you create a new project like I did above?

<img width="1241" alt="Screenshot 2021-06-09 at 10 23 33" src="https://user-images.githubusercontent.com/26437279/121329349-0b85ad80-c90d-11eb-95db-a3435d80661b.png">

**Comment by koogawa** [comment]
Hi @tcldr ,

When I created a new project with Xcode in Rosetta mode, I'm getting no build errors. I’d rather not use Rosetta mode because It's slow. But It seems difficult.

I appreciate your kind response.

**Comment by tcldr** [comment]
Hi @koogawa ,

No problem. I'm a little confused – I thought you were using Rosetta mode from the screenshot you posted!

I don't use Rosetta myself. That was the first time. Doing the same thing without Rosetta also works for me.

<img width="1247" alt="Screenshot 2021-06-09 at 14 08 50" src="https://user-images.githubusercontent.com/26437279/121360683-8ca06d00-c92c-11eb-82df-dda615f28ae4.png">

I notice you mention `Adding Any iOS Simulator SDK` with value `arm64` inside `Excluded Architecture`.

Could this be the cause?

**Comment by koogawa** [comment]
I'm sorry for the confusion. I don't use Rosetta from the beginning. 

I found https://stackoverflow.com/a/66094347/1155354 , This is same situation as me. So I'd like to use Rosetta. 😃

**Comment by tcldr** [comment]
Hi @koogawa,

So you have managed to resolve your issue?

To be clear, with a demo project Entwine compiles successfully on an M1 Mac both with and without Rosetta enabled for me.

**Comment by koogawa** [comment]
Hi @tcldr ,

Yes, I resolved my issue. Thank you for your kind response.

**Comment by tcldr** [comment]
Pleasure! Glad you found a fix
